
services: 
  proxy-database:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proxy-app
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - postgres_data:/var/lib/postgresql/data
  proxy-database-18:
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proxy-app-2
    ports:
      - 5433:5432
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
  redis: 
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: